name: release

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - uses: actions/checkout@v2

    - name: Cache Nuget
      uses: actions/cache@v2
      with:
        path: |
          !~/.nuget/packages/OpenSesame.*
          ~/.nuget/packages
        key: ${{ runner.os }}-nuget-packages-${{ hashFiles('**/eng/Versions.props') }}

    - name: Cache Node
      uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        
    - run: npm ci && npx semantic-release
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
