name: Release

on:
  push:
    branches:
      - master
      - alpha
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NUGET_PACKAGES: ${{ github.workspace }}/.nuget/packages

    steps:

    - uses: actions/checkout@v2

    - uses: actions/cache@v2
      with:
        path: ~/.nuget/packages
        key: ${{ runner.os }}-nuget
        restore-keys: ${{ runner.os }}-nuget-

    - uses: actions/cache@v2
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node
        restore-keys: ${{ runner.os }}-node-
        
    - run: npm ci && npx semantic-release
      env:
        NUGET_TOKEN: ${{ secrets.NUGET_TOKEN }}
        GITHUB_TOKEN: ${{ github.token }}
